public class TextGenerator {
    // takes two integer command-line arguments k and T, and prints T characters
    // generated by simulating a trajectory through the corresponding
    // Markov chain
    public static void main(String[] args) {
        int k = Integer.parseInt(args[0]);
        final int T = Integer.parseInt(args[1]);
        String text = StdIn.readAll();
        String kgram = text.substring(0, k);
        MarkovModel model = new MarkovModel(text, k);
        StdOut.print(kgram);
        for (int i = 0; i < T - k; i++) {
            char nChar = model.random(kgram);
            if (kgram.length() >= 1) {
                kgram = kgram.substring(1);
                kgram += nChar;
                StdOut.print(nChar);
            }
            else {
                StdOut.print(nChar);
            }
        }
    }
}
